apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-replicaset
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-api
  template:
    metadata:
      labels:
        app: pod-api
    spec:
      containers:
      - name: pod-api
        image: api-image:latest  
        ports:
        - containerPort: 5000  
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"  # A remplacer par le nom du service RabbitMQ dans Kubernetes
        - name: REDIS_HOST
          value: "redis-service"  # A remplacer par le nom du service Redis dans Kubernetes
        - name: API_HOST
          value: "0.0.0.0"  
        - name: API_PORT
          value: "5000"  
