apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-replicaset
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: flask-api
        image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/api-projet-my:Mahaut-Yohann
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq-service 
        - name: REDIS_HOST
          value: redis-service    
        - name: REDIS_PORT
          value: "6379"

