apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: consumer
  name: consumer-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-consumer
  template:
    metadata:
      labels:
        app: pod-consumer
    spec:
      containers:
      - name: pod-consumer
        image: consumer-image:latest  
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"  # Nom du service RabbitMQ dans Kubernetes
        - name: REDIS_HOST
          value: "redis-service"  # Nom du service Redis dans Kubernetes
        - name: CONSUMER_QUEUE
          value: "calculations"  # Nom de la queue que le consumer consomme
        
