apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: front-replicaset
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front 
  template:
    metadata:
      labels:
        app: front 
    spec:
      containers:
      - name: frontend-container
        image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/frontend-projet-my:Mahaut-Yohann
        ports:
        - name: http
          containerPort: 80
          protocol: TCP

