apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: redis
  name: redis-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisPod
  template:
    metadata:
      labels:
        app: redisPod
    spec:
      containers:
      - name: redis
        image: redis:latest  
        ports:
        - containerPort: 6379
        
